name: book_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  mongol: ^4.0.0
  flutter_screenutil: ^5.7.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  velocity_x: ^3.6.0
  rich_clipboard: ^1.0.1
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/json/
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: z52haratig
      fonts:
        - asset: assets/fonts/z52haratig.ttf
    - family: z52amglangtig
      fonts:
        - asset: assets/fonts/z52amgolangtig.ttf
    - family: z52buduntig
      fonts:
        - asset: assets/fonts/z52buduntig.ttf
    - family: z52chimegtig
      fonts:
        - asset: assets/fonts/z52chimegtig.ttf
    - family: z52egulentig
      fonts:
        - asset: assets/fonts/z52egulentig.ttf
    - family: z52hawangtig
      fonts:
        - asset: assets/fonts/z52hawangtig.ttf
    - family: z52holsnujugtig
      fonts:
        - asset: assets/fonts/z52holsnujugtig.ttf
    - family: z52horqtsagaantig
      fonts:
        - asset: assets/fonts/z52horqtsagaantig.ttf
    - family: z52munggunujugtig
      fonts:
        - asset: assets/fonts/z52munggunujugtig.ttf
    - family: z52ononsansseriftig
      fonts:
        - asset: assets/fonts/z52ononsansseriftig.ttf
    - family: z52ordostig
      fonts:
        - asset: assets/fonts/z52ordostig.ttf
    - family: z52qimedtig
      fonts:
        - asset: assets/fonts/z52qimedtig.ttf
    - family: z52qingmingtig
      fonts:
        - asset: assets/fonts/z52qingmingtig.ttf
    - family: z52saitig
      fonts:
        - asset: assets/fonts/z52sayatig.ttf
    - family: z52sanstig
      fonts:
        - asset: assets/fonts/z52sanstig.ttf
    - family: z52sanstigbold
      fonts:
        - asset: assets/fonts/z52sanstigbold.ttf
    - family: z52solibotig
      fonts:
        - asset: assets/fonts/z52solbigotig.ttf
    - family: z52sonintig
      fonts:
        - asset: assets/fonts/z52sonintig.ttf
    - family: z52togtig
      fonts:
        - asset: assets/fonts/z52togtig.ttf
    - family: z52tsagaantig
      fonts:
        - asset: assets/fonts/z52tsagaantig.ttf
    - family: z52uljitig
      fonts:
        - asset: assets/fonts/z52uljitig.ttf
    - family: z52erihetig
      fonts:
        - asset: assets/fonts/z52erihetig.ttf
    - family: z52galttig
      fonts:
        - asset: assets/fonts/z52galttig.ttf
    - family: z52modonbartig
      fonts:
        - asset: assets/fonts/z52modonbartig.ttf
    - family: z52sidemtig
      fonts:
        - asset: assets/fonts/z52sidemtig.ttf
    - family: z52togoraitig
      fonts:
        - asset: assets/fonts/z52togoraitig.ttf
    - family: z52oyanggatig
      fonts:
        - asset: assets/fonts/z52oyanggatig.ttf
    - family: z52holosontig
      fonts:
        - asset: assets/fonts/z52holosontig.ttf
    - family: z52garcagtig
      fonts:
        - asset: assets/fonts/z52garcagtig.ttf
    - family: z52tegustig
      fonts:
        - asset: assets/fonts/z52tegustig.ttf
    - family: z52durugetig
      fonts:
        - asset: assets/fonts/z52durugetig.ttf
    - family: z52hosigatig
      fonts:
        - asset: assets/fonts/z52hosigatig.ttf
    - family: z52lundbtig
      fonts:
        - asset: assets/fonts/z52lundbtig.ttf
    - family: z52sogonagtig
      fonts:
        - asset: assets/fonts/z52sogonagtig.ttf
    - family: z52teniguntig
      fonts:
        - asset: assets/fonts/z52teniguntig.ttf
    - family: z52ujugtig
      fonts:
        - asset: assets/fonts/z52ujugtig.ttf
    - family: z52xanadutig
      fonts:
        - asset: assets/fonts/z52xanadutig.ttf
    - family: z52oigorjintig
      fonts:
        - asset: assets/fonts/z52oigorjintig.ttf
    - family: z52sodortig
      fonts:
        - asset: assets/fonts/z52sodortig.ttf
    - family: z52tatalgatig
      fonts:
        - asset: assets/fonts/z52tatalgatig.ttf
    - family: z52agolatig
      fonts:
        - asset: assets/fonts/z52agolatig.ttf
    - family: z52daicintig
      fonts:
        - asset: assets/fonts/z52daicintig.ttf
    - family: z52tubtiintig
      fonts:
        - asset: assets/fonts/z52tubtiintig.ttf
    - family: z52dardastig
      fonts:
        - asset: assets/fonts/z52dardastig.ttf
    - family: z52dashtsedentig
      fonts:
        - asset: assets/fonts/z52dashtsedentig.ttf
    - family: z52boldbirtig
      fonts:
        - asset: assets/fonts/z52boldbirtig.ttf
    - family: z52gorbannirootig
      fonts:
        - asset: assets/fonts/z52gorbannirootig.ttf
    - family: z52biligtig
      fonts:
        - asset: assets/fonts/z52biligtig.ttf
    - family: z52khalhtig
      fonts:
        - asset: assets/fonts/z52khalhtig.ttf
    - family: z52tatalgantig
      fonts:
        - asset: assets/fonts/z52tatalgantig.ttf
    - family: z52tolitig
      fonts:
        - asset: assets/fonts/z52tolitig.ttf
    - family: z52enkiragotig
      fonts:
        - asset: assets/fonts/z52enkiragotig.ttf